# Port d'écoute
listening-port=3478
# (optionnel, si tu veux aussi TLS plus tard)
# tls-listening-port=5349

# Domaine/réalme (utilisé pour l’auth)
realm=donnarieix.fr

# Obligatoire pour que certains clients WebRTC fonctionnent
fingerprint

# On utilise l'authentification "long term" avec un user/pass statique
lt-cred-mech
user=webrtcuser:webrtcsupersecret

# Logs
simple-log
log-file=stdout

# Ports alloués pour relayer les flux RTP (range à ouvrir dans le firewall)
min-port=49160
max-port=49200

# Si ton serveur est directement en IP publique → rien à faire
# Si ton serveur est derrière un autre NAT, alors ajoute :
# external-ip=IP_PUBLIQUE
